# Generated by Django 3.1.1 on 2020-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
