# Generated by Django 3.1.1 on 2020-10-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201023_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo_url',
        ),
    ]
