# Generated by Django 3.1.1 on 2020-10-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_candidate_photo_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Representative',
        ),
    ]
