# Generated by Django 3.1.1 on 2020-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201023_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='representative',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
