# Generated by Django 3.1.1 on 2020-10-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_representative_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
