# Generated by Django 3.1.1 on 2020-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201108_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=1024, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Zip Code'),
        ),
    ]
