# Generated by Django 3.1.1 on 2020-10-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0003_auto_20201018_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='template',
        ),
    ]
