# Generated by Django 3.1.1 on 2020-10-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0005_auto_20201018_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
