# Generated by Django 3.1.1 on 2020-10-18 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0006_auto_20201018_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 18, 19, 27, 0, 912885)),
        ),
    ]
