# Generated by Django 3.1.1 on 2020-10-23 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0008_auto_20201018_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 2, 11, 16, 239973)),
        ),
    ]
