# Generated by Django 3.1.1 on 2020-10-23 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0011_auto_20201023_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 17, 59, 4, 805317)),
        ),
    ]
