# Generated by Django 3.1.1 on 2020-10-24 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0012_auto_20201023_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 14, 54, 195828)),
        ),
    ]
