# Generated by Django 3.1.1 on 2020-10-24 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0013_auto_20201023_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 20, 0, 121191)),
        ),
    ]
