# Generated by Django 3.1.1 on 2020-10-24 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0015_auto_20201023_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 54, 41, 409357)),
        ),
    ]
