# Generated by Django 3.1.1 on 2020-10-24 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0017_auto_20201024_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 14, 5, 49, 86084)),
        ),
    ]
