# Generated by Django 3.1.1 on 2020-11-09 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0022_auto_20201025_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 21, 7, 23, 556508)),
        ),
    ]
