# Generated by Django 3.1.1 on 2020-11-02 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0022_auto_20201025_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 22, 31, 18, 429192)),
        ),
    ]
