# Generated by Django 3.1.1 on 2020-11-09 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0023_auto_20201108_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 22, 6, 27, 927339)),
        ),
    ]
