# Generated by Django 3.1.1 on 2020-11-12 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0023_auto_20201101_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 2, 1, 59, 879077)),
        ),
    ]
