# Generated by Django 3.1.1 on 2020-11-09 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0024_auto_20201108_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 23, 54, 5, 309597)),
        ),
    ]
