# Generated by Django 3.1.1 on 2020-11-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0024_auto_20201112_0202'),
        ('civicconnect', '0025_auto_20201108_2354'),
    ]

    operations = [
    ]
