# Generated by Django 3.1.1 on 2020-11-17 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0026_auto_20201117_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 10, 15, 22, 654603)),
        ),
    ]
