# Generated by Django 3.1.1 on 2020-11-12 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0026_merge_20201112_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 2, 6, 39, 444634)),
        ),
    ]
