# Generated by Django 3.1.1 on 2020-11-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0027_auto_20201112_0206'),
        ('civicconnect', '0027_auto_20201117_1015'),
    ]

    operations = [
    ]
