# Generated by Django 3.1.1 on 2020-11-18 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0028_merge_20201117_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 22, 31, 46, 66930)),
        ),
    ]
