# Generated by Django 3.1.1 on 2020-11-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0029_auto_20201117_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
