# Generated by Django 3.1.1 on 2020-11-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civicconnect', '0030_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='approved',
        ),
    ]
